#!/usr/bin/perl

use strict;
use warnings;

my $dbname = "legion-test";
my $schwartz = "$dbname-schwartz";

system("dropdb '$dbname'");
system("dropdb '$schwartz'");

system("createdb '$dbname'");
system("createdb '$schwartz'");

system("psql '$dbname' -f db/legion.sql");

system("cd ../Legion-JobQueue/; psql '$schwartz' -f db/theschwartz.sql");
system("./script/legion_web_create.pl model DB DBIC::Schema Legion::Schema create=static dbi:Pg:dbname=$dbname");
system("rm storage_dir/*");
