#!/usr/bin/perl

use strict;
use warnings;

my $dbname = $ENV{DBNAME}
    or die "DBNAME must be specified";

system("dropdb '$dbname'");
system("createdb '$dbname'");
system("psql '$dbname' -f db/legion.sql");
system("cd ../Legion-JobQueue/; psql '$dbname' -f db/theschwartz.sql");
