package Legion::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Legion::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=legion-test',
        user => '',
        password => '',
    }
);

=head1 NAME

Legion::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Legion::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Legion::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

Orlando Vazquez

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
